### ISSUE TITLE
Does it work on Windows 7 operating systems?

### ISSUE THREAD

**Issue by GibbOne** [bryceg/Owin.WebSocket#26]
Otherwise do you think to add support for it?
Thx.

**Comment by GibbOne** [comment]
I guess it means no :-(.

**Comment by jacobrayschwartz** [comment]
So, since it took me a while to google, I'll add the answer here. This library cannot support Windows 7 because System.Net.Websockets is only supported on Windows 8 and higher, it relies on the OS support that was only added then. 

See: https://stackoverflow.com/questions/11039438/using-websocket-on-windows-7
