### ISSUE TITLE
Debug outputs to ..\build - is this the intent?

### ISSUE THREAD

**Issue by ca-ta** [bryceg/Owin.WebSocket#5]
Hi Bryce,

First, thank you for putting together Owin.WebSocket - It's great :+1: 

I've noticed that the nugget spec picks up ```Owin.WebSocket.dll``` from ```src\build```. However, currently only the Debug configuration outputs to that folder. It would seem that the debug version of the dll is packaged in the Nuget - is this intentional?

**Comment by bryceg** [comment]
Just an oversight, I’ll put together a release build this week.





From: Catalin Bocirnea
Sent: ‎Saturday‎, ‎March‎ ‎28‎, ‎2015 ‎6‎:‎34‎ ‎PM
To: bryceg/Owin.WebSocket





Hi Bryce,

First, thank you for putting together Owin.WebSocket - It's great  :+1: 

I've noticed that the nugget spec picks up Owin.WebSocket.dll from src\build. However, currently only the Debug configuration outputs to that folder. It would seem that the debug version of the dll is packaged in the Nuget - is this intentional?

**Comment by ca-ta** [comment]
Cool, thanks! 

I can make that change (e.g. make the Release configuration output to src/build instead of Debug ) and submit it as part of a PR I am working it that adds asynchronous handlers for OnOpen, OnClose and AuthenticateRequest -  if that's OK with you.

**Comment by bryceg** [comment]
Sure, make a PR and I'll take a look at it.

**Comment by ca-ta** [comment]
@briceg - PR #6 submitted

**Comment by bryceg** [comment]
pushed 1.4 to nuget with these changes

**Comment by ca-ta** [comment]
@bryceg Thanks Bryce!
